program = <whitespace> (expression <whitespace>)*
expression = <"("> form (<required_space> form)* <")">
<form> = symbol | number | expression
symbol = #'[^\s\d][^\s]*'
number = #'[\d]+'
<required_space> = #'\s+'
<whitespace> = #'\s*'
